            - name: Gitlab Sync
  # You may pin to the exact commit or the version.
  # uses: action-pack/gitlab-sync@38077a591a7f2ceb6ff6026e6beb2954a3be0f93
  uses: action-pack/gitlab-sync@v3.03
  with:
    # GitLab repo URL
    url: ${{ secret.GITLAB_REPOSITORY }}
    # GitLab username
    username: ${{ secret.GITLAB_USERNAME }}
    # GitLab token
    token: ${{ secret.MIRRORING_PAT }}
          
