name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      
      - name: Map tokenized URL for this host
        run: |
          git config --local url."https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.MIRRORING_PAT }}@lab.i4624.info/".insteadOf "https://lab.i4624.info/"
      
      - name: Add remote & push
        run: |
          git remote remove target 2>/dev/null || true
          git remote add target https://lab.i4624.info/good-restaurant/gs-database.git
          git ls-remote target 1>/dev/null
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            BR="${GITHUB_REF#refs/heads/}"
            git push target "$BR:$BR" --force-with-lease
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TG="${GITHUB_REF#refs/tags/}"
            git push target "refs/tags/$TG:refs/tags/$TG" --force-with-lease
          fi

