name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # # 선택: 러너 IP를 Cloudflare에 임시 허용 (없으면 자동으로 건너뜀)
      # - name: Bypass Cloudflare for this job (optional)
      #   if: ${{ secrets.CF_ZONE_ID && secrets.CF_API_TOKEN }}
      #   uses: esetnik/bypass-cloudflare-for-github-action@v3
      #   with:
      #     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
      #     cf_api_token: ${{ secrets.CF_API_TOKEN }}

      - name: Mirror to GitLab via Cloudflare Access
        env:
          GITLAB_REPO: https://lab.i4624.info/good-restaurant/gs-database.git
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.MIRRORING_PAT }}
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: |
          set -euo pipefail

          # 디버깅: 토큰 해시만 출력(값 유출 방지)
          printf '%s' "$GITLAB_TOKEN" | sha256sum

          # Cloudflare Access + Basic Auth 헤더를 -c로 주입할 준비
          BASE_URL="https://lab.i4624.info/"

          # Basic Auth (username:PAT → base64)
          AUTH="$(printf '%s:%s' "$GITLAB_USERNAME" "$GITLAB_TOKEN" | base64 -w0 2>/dev/null || printf '%s:%s' "$GITLAB_USERNAME" "$GITLAB_TOKEN" | base64)"

          H1="-c http.${BASE_URL}.extraheader=Authorization: Basic $AUTH"
          H2="-c http.${BASE_URL}.extraheader=CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
          H3="-c http.${BASE_URL}.extraheader=CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"

          # 연결 확인 (필요시 GIT_CURL_VERBOSE=1로 더 상세로그)
          git $H1 $H2 $H3 ls-remote "$GITLAB_REPO" >/dev/null

          # remote 재설정 후 push
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "$GITLAB_REPO"

          CUR=$(git rev-parse --abbrev-ref HEAD)

          # 브랜치와 태그 동기화 (GitLab에서 CI 돌리기 싫으면 -o ci.skip 유지)
          git $H1 $H2 $H3 push gitlab "$CUR:$CUR" -o ci.skip --force-with-lease
          git $H1 $H2 $H3 push gitlab --tags -o ci.skip --force-with-lease
