name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']
  # 삭제 이벤트까지 미러링하려면 아래 주석 해제
  # delete: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GIT_TERMINAL_PROMPT: 0
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
        
      - name: Inject Basic auth for lab.i4624.info
        run: |
          AUTH="$(printf '%s:%s' '${{ secrets.GITLAB_USERNAME }}' '${{ secrets.MIRRORING_PAT }}' | base64 -w0 2>/dev/null || base64 -b0)"
          git config --global http.https://lab.i4624.info/.extraheader "Authorization: Basic $AUTH"
          git remote remove target 2>/dev/null || true
          git remote add target https://lab.i4624.info/good-restaurant/gs-database.git
          git ls-remote --heads target 1>/dev/null
          BR="${GITHUB_REF#refs/heads/}"
          git push target "$BR:$BR" --force-with-lease

      - name: Push tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TG="${GITHUB_REF#refs/tags/}"
          # 태그는 덮어쓸 일이 잦으면 --force 권장
          git push target "refs/tags/$TG:refs/tags/$TG" --force

      # 삭제 미러링(선택)
      # - name: Mirror deletes
      #   if: ${{ github.event_name == 'delete' }}
      #   run: |
      #     if [[ "${{ github.event.ref_type }}" == "branch" ]]; then
      #       git push target ":${{ github.event.ref }}"
      #     elif [[ "${{ github.event.ref_type }}" == "tag" ]]; then
      #       git push target ":refs/tags/${{ github.event.ref }}"
      #     fi
