name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 선택: 러너 IP를 Cloudflare에 임시 허용 (잡 시작 시 추가, 끝나면 제거)
      # secrets 가 설정되어 있지 않으면 이 step은 건너뜁니다.
      - name: Bypass Cloudflare for this job (optional)
        if: ${{ secrets.CF_ZONE_ID && secrets.CF_API_TOKEN }}
        uses: esetnik/bypass-cloudflare-for-github-action@v3
        with:
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}

      - name: Mirror to GitLab
        env:
          GITLAB_REPO: https://lab.i4624.info/good-restaurant/gs-database.git
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}   # 개인 PAT면 본인 username
          GITLAB_TOKEN: ${{ secrets.MIRRORING_PAT }}        # write_repository 포함
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: |
          set -e

          # 디버깅용: 토큰 해시만 출력 (값 유출 방지)
          printf '%s' "$GITLAB_TOKEN" | sha256sum

          # GitLab Basic Auth 헤더
          AUTH="$(printf '%s:%s' "$GITLAB_USERNAME" "$GITLAB_TOKEN" | base64 -w0 2>/dev/null || printf '%s:%s' "$GITLAB_USERNAME" "$GITLAB_TOKEN" | base64)"

          # URL-스코프별 extraheader 지정(다른 호스트로 새지 않도록)
          GIT_URL="https://lab.i4624.info/"
          git config --global "http.${GIT_URL}.extraheader" "Authorization: Basic $AUTH"
          git config --global "http.${GIT_URL}.extraheader" "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
          git config --global "http.${GIT_URL}.extraheader" "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"

          # 접근 확인
          git ls-remote "$GITLAB_REPO" >/dev/null

          # remote 설정 및 push
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "$GITLAB_REPO"

          CUR=$(git rev-parse --abbrev-ref HEAD)

          # 브랜치 & 태그 푸시 (force-with-lease 유지)
          git push gitlab "$CUR:$CUR" -o ci.skip -f --force-with-lease
          git push gitlab --tags -o ci.skip --force-with-lease
