name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_HOSTPATH: lab.i4624.info/good-restaurant/gs-database.git  ## 앞의 https 제거
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.MIRRORING_PAT }}
        run: |
          #  https는 여기서만 한 번 붙임
          ## 토큰 유효성 확인
          curl -fsS -H "PRIVATE-TOKEN: $GITLAB_TOKEN" https://lab.i4624.info/api/v4/user
          
          ## 프로젝트 접근권한 확인  group/project URL 인코딩 필요
          curl -fsS -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://lab.i4624.info/api/v4/projects/good-restaurant%2Fgs-database" | jq '.permissions'

          
          git remote add gitlab "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${GITLAB_HOSTPATH}"
          git push --all gitlab
          git push --tags gitlab


