name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_REPO: https://lab.i4624.info/good-restaurant/gs-database.git
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}   ## 개인 PAT면 본인 username
          GITLAB_TOKEN: ${{ secrets.MIRRORING_PAT }}        ## write_repository 포함
        run: |
          set -e
          AUTH="$(printf '%s:%s' "$GITLAB_USERNAME" "$GITLAB_TOKEN" | base64 -w0 2>/dev/null || base64 -b0)"
      
          ## 한국어 주석  인증 확인
          git -c http.extraheader="Authorization: Basic $AUTH" ls-remote "$GITLAB_REPO" >/dev/null
      
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "$GITLAB_REPO"
      
          CUR=$(git rev-parse --abbrev-ref HEAD)
          git -c http.extraheader="Authorization: Basic $AUTH" push gitlab "$CUR:$CUR"
          git -c http.extraheader="Authorization: Basic $AUTH" push gitlab --tags


