name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_HOST_PATH: lab.i4624.info/good-restaurant/gs-database.git  ## 중요: https 제거, 슬래시 꼬리 제거
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.MIRRORING_PAT }}
        run: |
          set -e
          echo "remote = https://${GITLAB_USERNAME}:***@${GITLAB_HOST_PATH}"
          git remote add gitlab "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${GITLAB_HOST_PATH}"
          git push --all gitlab
          git push --tags gitlab
