name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_HOSTPATH: lab.i4624.info/good-restaurant/gs-database.git  ## 앞의 https 제거
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.MIRRORING_PAT }}
        run: |
          # 한국어 주석  https는 여기서만 한 번 붙임
          git remote add gitlab "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${GITLAB_HOSTPATH}"
          git push --all gitlab
          git push --tags gitlab


