name: GitLab Sync

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        # uses: action-pack/gitlab-sync@38077a591a7f2ceb6ff6026e6beb2954a3be0f93
        env:
          url: ${{ secrets.GITLAB_REPOSITORY }}   # 예: https://gitlab.com/group/project.git
          username: ${{ secrets.GITLAB_USERNAME }} # GitLab 사용자명 (보통 email 대신 username)
          token: ${{ secrets.MIRRORING_PAT }}      # GitLab Personal Access Token
        run: | # 모든 브랜치와 태그에 대하여 push합니다. gitlab에서 보호설정이 걸려있으면 Fail할 수 있습니다.
          git remote add gitlab https://${username}:${token}@${url};
          git push -f --all gitlab;
          git push -f --tags gitlab;
            
